### ISSUE TITLE
variable naming

### ISSUE THREAD

**Issue by Clercq** [parcellaann/PendingInitDelete#2]
https://github.com/parcellaann/PendingInitDelete/blob/039804867f55b771754b0fac9c082d105871e078/src/main/java/com/pendinginitdelete/Main.java#L20

https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html

**Comment by Clercq** [comment]
![image](https://github.com/parcellaann/PendingInitDelete/assets/50501391/5ca09ff6-3a19-4642-8557-56c033bfd7be)

**Comment by parcellaann** [comment]
Fixed, thanks!
